DELETE FROM `users_roles`;
DELETE FROM `article`;
DELETE FROM `article_tags`;
DELETE FROM `tag`;
DELETE FROM `category`;
DELETE FROM `users`;
DELETE FROM `roles`;
DELETE FROM `article`;



INSERT INTO `users` (`active`,`credentials_expiration_date`,`expiration_date`,`locked`,`password`,`username`,`first_name`,`last_name`,`email`)
VALUES (1,'2020-01-01','2020-01-01',0,'$2a$10$8Zs9WYLX77m5T.EIthx4CupwaCJ1DNX0IRDdhPJmIgdT/XJZjvrum','adf','Abderahmane','DIAF','a.diaf@outlook.fr');

INSERT INTO `roles` (`role_name`) VALUES ('ROLE_ADMIN');
INSERT INTO `roles` (`role_name`) VALUES ('ROLE_USER');

INSERT INTO `users_roles` VALUES (1,1);
INSERT INTO `users_roles` VALUES (1,2);

INSERT INTO `category` (`name`,`description`,`category_level`) VALUES ("PE","4708 Nunc, St.",0);
INSERT INTO `category` (`name`,`description`,`category_level`) VALUES ("WI","957-7973 At Street",0);
INSERT INTO `category` (`name`,`description`,`category_level`) VALUES ("ANT","Ap #123-9952 Pede, Rd.",0);
INSERT INTO `category` (`name`,`description`,`category_level`) VALUES ("W","Ap #688-4163 Praesent Street",0);
INSERT INTO `category` (`name`,`description`,`category_level`) VALUES ("New South Wales","5200 Vitae Street",0);
INSERT INTO `category` (`name`,`description`,`category_level`) VALUES ("Chelyabinsk Oblast","405-5436 Mi, Rd.",0);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("SAR","Ap #765-8396 Sollicitudin Av.",1,1);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("CHE","Ap #108-1164 Vitae Avenue",1,1);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("AMU","P.O. Box 224, 7316 At Rd.",1,2);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("Atlántico","586-1109 Interdum. Rd.",1,3);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("North Island","3013 Congue. Street",1,1);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("KN","443-8004 Tincidunt St.",1,3);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("Akwa Ibom","P.O. Box 747, 8997 Odio. Road",1,5);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("Dolnośląskie","P.O. Box 303, 8487 Eu St.",1,5);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("Victoria","1956 Convallis, St.",2,8);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("Ancash","P.O. Box 146, 2282 Non, St.",2,6);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("ON","P.O. Box 326, 3007 Sed Rd.",2,7);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("North Island","P.O. Box 719, 5856 Imperdiet Avenue",2,10);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("MH","Ap #405-9035 Mi Ave",2,7);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("PR","2781 Quam, St.",2,11);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("NW","P.O. Box 125, 7891 Suspendisse Road",2,7);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("Emilia-Romagna","204-5883 Id Av.",2,8);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("C","P.O. Box 943, 6603 Aliquam St.",2,9);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("Devon","P.O. Box 112, 1897 Euismod Av.",2,10);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("NI","Ap #588-7040 Leo. Ave",2,8);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("BU","760-6563 Praesent Ave",2,11);
INSERT INTO `category` (`name`,`description`,`category_level`,`parent_category_id`) VALUES ("HI","783-3848 Mauris Street",2,10);


INSERT INTO `article` (`name`,`description`) VALUES ("Benedict E. Hyde","Greenland");
INSERT INTO `article` (`name`,`description`) VALUES ("Kylee F. Owens","Togo");
INSERT INTO `article` (`name`,`description`) VALUES ("Nicole F. Bowers","Cyprus");
INSERT INTO `article` (`name`,`description`) VALUES ("Amaya A. Rowland","Guatemala");
INSERT INTO `article` (`name`,`description`) VALUES ("Hall Q. Park","Malaysia");
INSERT INTO `article` (`name`,`description`) VALUES ("Chase R. Powell","Fiji");
INSERT INTO `article` (`name`,`description`) VALUES ("Kylee C. Schwartz","Aruba");
INSERT INTO `article` (`name`,`description`) VALUES ("Silas A. Phelps","Philippines");
INSERT INTO `article` (`name`,`description`) VALUES ("Jack T. Knowles","Cape Verde");
INSERT INTO `article` (`name`,`description`) VALUES ("Cherokee Z. Brock","Mongolia");
INSERT INTO `article` (`name`,`description`) VALUES ("Lara M. Miranda","Tanzania");
INSERT INTO `article` (`name`,`description`) VALUES ("Olivia Y. Rosales","Somalia");
INSERT INTO `article` (`name`,`description`) VALUES ("Jonas U. Woodward","British Indian Ocean Territory");
INSERT INTO `article` (`name`,`description`) VALUES ("Warren Y. Gilbert","Tunisia");
INSERT INTO `article` (`name`,`description`) VALUES ("Dakota G. Mueller","Maldives");
INSERT INTO `article` (`name`,`description`) VALUES ("Ignatius L. Christensen","Hungary");
INSERT INTO `article` (`name`,`description`) VALUES ("Paki Q. Delgado","Saint Martin");
INSERT INTO `article` (`name`,`description`) VALUES ("Dane X. Dyer","Mauritius");
INSERT INTO `article` (`name`,`description`) VALUES ("Nerea J. Hess","Belarus");
INSERT INTO `article` (`name`,`description`) VALUES ("Myles E. Thomas","Philippines");
INSERT INTO `article` (`name`,`description`) VALUES ("Daryl G. Mckenzie","Cayman Islands");
INSERT INTO `article` (`name`,`description`) VALUES ("Nissim M. Carpenter","Morocco");
INSERT INTO `article` (`name`,`description`) VALUES ("Jamalia U. Frazier","Madagascar");
INSERT INTO `article` (`name`,`description`) VALUES ("Hayden C. Downs","Bolivia");
INSERT INTO `article` (`name`,`description`) VALUES ("Neve D. Stewart","Ethiopia");
INSERT INTO `article` (`name`,`description`) VALUES ("Georgia W. Blankenship","Côte D'Ivoire (Ivory Coast)");
INSERT INTO `article` (`name`,`description`) VALUES ("Murphy F. Butler","Solomon Islands");
INSERT INTO `article` (`name`,`description`) VALUES ("Hop T. Pennington","Puerto Rico");
INSERT INTO `article` (`name`,`description`) VALUES ("Raven M. Allen","Slovenia");
INSERT INTO `article` (`name`,`description`) VALUES ("Zenaida Y. Kirby","Lebanon");
INSERT INTO `article` (`name`,`description`) VALUES ("Dennis M. Henry","Argentina");
INSERT INTO `article` (`name`,`description`) VALUES ("Halla X. Potter","Rwanda");
INSERT INTO `article` (`name`,`description`) VALUES ("Laith G. Potter","Bolivia");
INSERT INTO `article` (`name`,`description`) VALUES ("Hedley G. Weeks","Sri Lanka");
INSERT INTO `article` (`name`,`description`) VALUES ("Hashim X. Mccullough","Finland");
INSERT INTO `article` (`name`,`description`) VALUES ("Preston X. Morton","Viet Nam");
INSERT INTO `article` (`name`,`description`) VALUES ("Natalie F. Macias","Albania");
INSERT INTO `article` (`name`,`description`) VALUES ("Yoshio B. Ray","France");
INSERT INTO `article` (`name`,`description`) VALUES ("Kasper C. Morse","Cayman Islands");
INSERT INTO `article` (`name`,`description`) VALUES ("Sylvia Y. Mooney","Algeria");
INSERT INTO `article` (`name`,`description`) VALUES ("Hector R. Hoover","Spain");
INSERT INTO `article` (`name`,`description`) VALUES ("Kendall S. Ferrell","Brunei");
INSERT INTO `article` (`name`,`description`) VALUES ("Chanda I. Guthrie","Kyrgyzstan");
INSERT INTO `article` (`name`,`description`) VALUES ("George L. Strickland","Svalbard and Jan Mayen Islands");
INSERT INTO `article` (`name`,`description`) VALUES ("Alan R. Powell","Albania");
INSERT INTO `article` (`name`,`description`) VALUES ("Raymond A. Burris","Sierra Leone");
INSERT INTO `article` (`name`,`description`) VALUES ("Tobias L. Rosa","Cyprus");
INSERT INTO `article` (`name`,`description`) VALUES ("Linus D. Crane","Congo, the Democratic Republic of the");
INSERT INTO `article` (`name`,`description`) VALUES ("Kylan O. Barber","Ukraine");
INSERT INTO `article` (`name`,`description`) VALUES ("Rachel F. Ramos","Malawi");
INSERT INTO `article` (`name`,`description`) VALUES ("Moana Z. Franklin","Bolivia");
INSERT INTO `article` (`name`,`description`) VALUES ("Candice L. Guy","Malawi");
INSERT INTO `article` (`name`,`description`) VALUES ("Hop J. Mccall","Marshall Islands");
INSERT INTO `article` (`name`,`description`) VALUES ("James H. Greer","Cape Verde");
INSERT INTO `article` (`name`,`description`) VALUES ("Chancellor N. Schwartz","Netherlands");
INSERT INTO `article` (`name`,`description`) VALUES ("Shad P. Gilmore","Israel");
INSERT INTO `article` (`name`,`description`) VALUES ("Garth L. Parks","Grenada");
INSERT INTO `article` (`name`,`description`) VALUES ("Nathan K. Barker","Korea, North");
INSERT INTO `article` (`name`,`description`) VALUES ("Abigail T. Cline","Bermuda");
INSERT INTO `article` (`name`,`description`) VALUES ("Conan T. Nielsen","Niger");
INSERT INTO `article` (`name`,`description`) VALUES ("Hunter G. Gregory","Falkland Islands");
INSERT INTO `article` (`name`,`description`) VALUES ("Carla B. Williamson","Benin");
INSERT INTO `article` (`name`,`description`) VALUES ("Xantha S. Knight","Gambia");
INSERT INTO `article` (`name`,`description`) VALUES ("Kenneth C. Stevens","Mayotte");
INSERT INTO `article` (`name`,`description`) VALUES ("Drew F. Lindsay","China");
INSERT INTO `article` (`name`,`description`) VALUES ("Susan L. Forbes","Isle of Man");
INSERT INTO `article` (`name`,`description`) VALUES ("Hasad E. Jones","Korea, North");
INSERT INTO `article` (`name`,`description`) VALUES ("Tarik T. Boyd","Iceland");
INSERT INTO `article` (`name`,`description`) VALUES ("Ava H. Park","Nigeria");
INSERT INTO `article` (`name`,`description`) VALUES ("Kyle R. Spencer","Zimbabwe");
INSERT INTO `article` (`name`,`description`) VALUES ("Aline V. Welch","Seychelles");
INSERT INTO `article` (`name`,`description`) VALUES ("Karina R. Sosa","South Sudan");
INSERT INTO `article` (`name`,`description`) VALUES ("Germaine I. Rhodes","Cocos (Keeling) Islands");
INSERT INTO `article` (`name`,`description`) VALUES ("Diana K. Colon","Czech Republic");
INSERT INTO `article` (`name`,`description`) VALUES ("Ian E. Poole","Tonga");
INSERT INTO `article` (`name`,`description`) VALUES ("Nasim K. Bernard","Macedonia");
INSERT INTO `article` (`name`,`description`) VALUES ("Eleanor G. Glover","Nauru");
INSERT INTO `article` (`name`,`description`) VALUES ("Renee S. Simpson","Swaziland");
INSERT INTO `article` (`name`,`description`) VALUES ("Moses S. Nixon","Uganda");
INSERT INTO `article` (`name`,`description`) VALUES ("Alfonso J. Levine","Poland");
INSERT INTO `article` (`name`,`description`) VALUES ("Rhoda U. Clayton","Oman");
INSERT INTO `article` (`name`,`description`) VALUES ("Herrod O. Barrett","Czech Republic");
INSERT INTO `article` (`name`,`description`) VALUES ("Ariel J. Simon","Ireland");
INSERT INTO `article` (`name`,`description`) VALUES ("Wynter N. Logan","Brunei");
INSERT INTO `article` (`name`,`description`) VALUES ("George Z. Osborne","Turkmenistan");
INSERT INTO `article` (`name`,`description`) VALUES ("Willa P. Schwartz","Macao");
INSERT INTO `article` (`name`,`description`) VALUES ("Kay H. Miranda","Mauritius");
INSERT INTO `article` (`name`,`description`) VALUES ("Roanna Z. Parks","Guinea-Bissau");
INSERT INTO `article` (`name`,`description`) VALUES ("Duncan J. Mcdowell","Malta");
INSERT INTO `article` (`name`,`description`) VALUES ("Colton X. Barlow","Saint Barthélemy");
INSERT INTO `article` (`name`,`description`) VALUES ("Chaney E. Spencer","Syria");
INSERT INTO `article` (`name`,`description`) VALUES ("Axel R. Delacruz","Myanmar");
INSERT INTO `article` (`name`,`description`) VALUES ("Lani Q. Diaz","Bosnia and Herzegovina");
INSERT INTO `article` (`name`,`description`) VALUES ("Kathleen U. Hardin","Mexico");
INSERT INTO `article` (`name`,`description`) VALUES ("Ciaran J. Benton","Denmark");
INSERT INTO `article` (`name`,`description`) VALUES ("Ulric Z. Bryant","Saint Helena, Ascension and Tristan da Cunha");
INSERT INTO `article` (`name`,`description`) VALUES ("Andrew N. Madden","Germany");
INSERT INTO `article` (`name`,`description`) VALUES ("Slade W. Hatfield","Virgin Islands, British");
INSERT INTO `article` (`name`,`description`) VALUES ("Geoffrey P. Hawkins","Cuba");
INSERT INTO `article` (`name`,`description`) VALUES ("Abra K. Acevedo","Switzerland");


INSERT INTO `tag` (`name`,`description`) VALUES ("Fort Smith","5385 Pede. Avenue");
INSERT INTO `tag` (`name`,`description`) VALUES ("Villafranca d'Asti","Ap #130-6296 Eu Ave");
INSERT INTO `tag` (`name`,`description`) VALUES ("Stupino","P.O. Box 341, 3345 Commodo Avenue");
INSERT INTO `tag` (`name`,`description`) VALUES ("Schaarbeek","244-5081 Nisi. St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Kech","5564 Ac St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Meeuwen-Gruitrode","8477 Purus Road");
INSERT INTO `tag` (`name`,`description`) VALUES ("Couture-Saint-Germain","9509 Nulla Av.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Aberystwyth","P.O. Box 150, 1617 Tincidunt, Avenue");
INSERT INTO `tag` (`name`,`description`) VALUES ("Stirling","8680 Faucibus Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("My","778-1353 Semper Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Conca Casale","3770 At, Av.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Zeebrugge","7566 Mauris Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Libramont-Chevigny","4781 Sagittis Road");
INSERT INTO `tag` (`name`,`description`) VALUES ("Courcelles","279-4293 Elementum, Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Whangarei","725 Sit Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Molino dei Torti","629-120 Mauris St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Camrose","P.O. Box 983, 7404 Et Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("College","P.O. Box 620, 7067 Nunc Av.");
INSERT INTO `tag` (`name`,`description`) VALUES ("San Rosendo","P.O. Box 128, 7724 Quis, Av.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Calera","9013 Tempus St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Dunfermline","P.O. Box 969, 3908 Faucibus Av.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Marche-les-Dames","Ap #922-4753 Dui Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Minna","403-5507 Faucibus Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Penicuik","8111 Aenean Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Cabras","P.O. Box 319, 4772 Malesuada Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Tielen","118-8617 Donec Road");
INSERT INTO `tag` (`name`,`description`) VALUES ("Coaldale","Ap #284-239 Dui Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Balfour","3604 Integer Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Castellina in Chianti","Ap #166-3517 Gravida Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Waarloos","P.O. Box 825, 6017 Tempor Ave");
INSERT INTO `tag` (`name`,`description`) VALUES ("Krishnanagar","369-1588 Lorem St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Campochiaro","1479 Dui, Avenue");
INSERT INTO `tag` (`name`,`description`) VALUES ("Navadwip","Ap #237-9091 Tellus St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Kempten","2052 Laoreet, St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Colombo","288 Donec Ave");
INSERT INTO `tag` (`name`,`description`) VALUES ("Curanilahue","Ap #561-4787 Nunc Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Jamnagar","3597 Ad Av.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Cupar","P.O. Box 631, 7531 Magna. Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Torres del Paine","9800 Vitae Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Latour","892-6231 Maecenas Av.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Bhopal","6606 Sed, Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Siddi","P.O. Box 298, 8689 Nec Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Asan","Ap #599-4160 Cursus Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Vannes","3289 Netus St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("La Granja","Ap #271-2492 Egestas Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Villahermosa","Ap #691-8907 Magnis Avenue");
INSERT INTO `tag` (`name`,`description`) VALUES ("Brighton","8014 Sem Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Beaconsfield","Ap #364-347 Sit Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Vremde","P.O. Box 716, 5368 Integer Road");
INSERT INTO `tag` (`name`,`description`) VALUES ("Diets-Heur","Ap #252-5334 Diam Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Vorst","9708 Nulla Avenue");
INSERT INTO `tag` (`name`,`description`) VALUES ("Orai","6805 Suspendisse Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Portree","P.O. Box 712, 2378 Luctus Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Amsterdam","389-2569 Ipsum St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Zamora","740-7589 Scelerisque Ave");
INSERT INTO `tag` (`name`,`description`) VALUES ("Épernay","P.O. Box 712, 6711 Feugiat Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Rosciano","P.O. Box 147, 1597 Sapien. Ave");
INSERT INTO `tag` (`name`,`description`) VALUES ("Maranguape","P.O. Box 701, 5722 Sollicitudin St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Solapur","3958 Magna. Av.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Jerez de la Frontera","P.O. Box 674, 4399 Nullam Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Dion-Valmont","5436 Aliquet St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Hay River","P.O. Box 460, 3956 At, St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Kirkintilloch","520-3635 Phasellus Avenue");
INSERT INTO `tag` (`name`,`description`) VALUES ("Draguignan","Ap #391-7346 Velit Avenue");
INSERT INTO `tag` (`name`,`description`) VALUES ("Cambridge Bay","159-2908 Pellentesque St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Watson Lake","2623 Turpis. Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Fauvillers","Ap #750-5297 Non, Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Maullín","1950 Metus. Ave");
INSERT INTO `tag` (`name`,`description`) VALUES ("Glendale","131-7063 Netus Road");
INSERT INTO `tag` (`name`,`description`) VALUES ("Verona","1744 Est Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Maule","2252 Nunc St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Torrejón de Ardoz","693 Nonummy. Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Armidale","Ap #140-8267 Cras St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Bruck an der Mur","3860 Lacus, Avenue");
INSERT INTO `tag` (`name`,`description`) VALUES ("Burin","Ap #847-7461 Nulla Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Blairgowrie","6745 Cursus. Av.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Empedrado","6387 Aliquam Road");
INSERT INTO `tag` (`name`,`description`) VALUES ("St. David's","8765 Ipsum Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Seraing","Ap #581-6449 Vitae Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Coleville Lake","6687 Fringilla, Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Penhold","212-5650 Convallis Street");
INSERT INTO `tag` (`name`,`description`) VALUES ("Emarèse","697-7402 Adipiscing Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Longvilly","Ap #652-727 Suspendisse St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Almería","2240 Mollis Road");
INSERT INTO `tag` (`name`,`description`) VALUES ("Grande Cache","Ap #684-1160 Tempor Av.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Silchar","P.O. Box 241, 6193 Orci. St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Musson","Ap #935-1398 Etiam Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Sautin","465 Turpis. Road");
INSERT INTO `tag` (`name`,`description`) VALUES ("Leiden","P.O. Box 929, 3437 Metus St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Sotteville-lès-Rouen","P.O. Box 457, 2065 Quis Avenue");
INSERT INTO `tag` (`name`,`description`) VALUES ("Ghaziabad","Ap #101-3531 Metus. Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Colchester","605-4544 Enim. Av.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Elmshorn","P.O. Box 117, 6370 Metus. Ave");
INSERT INTO `tag` (`name`,`description`) VALUES ("New Orleans","242-3735 Magnis Avenue");
INSERT INTO `tag` (`name`,`description`) VALUES ("Bonneville","Ap #374-9674 Et St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Filignano","Ap #405-7690 Facilisis Rd.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Ostra Vetere","P.O. Box 361, 6756 Sapien St.");
INSERT INTO `tag` (`name`,`description`) VALUES ("Port Alice","P.O. Box 352, 3284 Condimentum. Avenue");
INSERT INTO `tag` (`name`,`description`) VALUES ("Ripabottoni","Ap #145-3855 Lobortis Ave");
INSERT INTO `tag` (`name`,`description`) VALUES ("Anamur","410-8996 Diam. Street");