DELETE FROM `farmer`;
DELETE FROM `users_roles`;
DELETE FROM `users`;
DELETE FROM `roles`;
DELETE FROM `article`;


INSERT INTO `farmer` (`id`,`name`,`village`) VALUES (1,"Xena Tyson","Khyber Pakhtoonkhwa"),(2,"Mason Santana","U."),(3,"Evelyn Hensley","SJ"),(4,"Cleo Hays","NB"),(5,"Jemima Dillard","RS"),(6,"Quintessa Dillon","Wigtownshire"),(7,"Hop Dickerson","CE"),(8,"Madaline Ramos","AB"),(9,"Kiona Blair","C"),(10,"Casey Sloan","Maule"),(11,"Uriel Sanders","SP"),(12,"Alfreda Schmidt","Ulyanovsk Oblast"),(13,"Audra Gross","JI"),(14,"Chester Barrett","Pays de la Loire"),(15,"Linus Gaines","PR"),(16,"Steven Key","LU"),(17,"Jin Graham","Brussels Hoofdstedelijk Gewest"),(18,"Lisandra Ortega","Noord Brabant"),(19,"Illana Townsend","Maranhão"),(20,"Neville Knox","Cusco"),(21,"Aaron Gibson","North Island"),(22,"Ralph Byers","Gävleborgs län"),(23,"Kamal Sanchez","Tarapacá"),(24,"Brady Walters","Małopolskie"),(25,"Melodie Reilly","Île-de-France"),(26,"Hamish Blankenship","São Paulo"),(27,"Baker Acevedo","Hamburg"),(28,"Priscilla Stevens","PE"),(29,"Mercedes Watson","P"),(30,"Allen Ware","NA"),(31,"Ila Gonzales","AK"),(32,"Luke Terry","Dalarnas län"),(33,"Eleanor Fletcher","Brussels Hoofdstedelijk Gewest"),(34,"Quinlan Manning","North Island"),(35,"Callie Mercado","Berlin"),(36,"Len Torres","QC"),(37,"Zenaida Cruz","ANT"),(38,"Brendan Kent","O"),(39,"Lana Martin","Mexico City"),(40,"Cheyenne Riley","Caithness"),(41,"Reece Sheppard","Ov"),(42,"Francis Lancaster","PO"),(43,"Lila Melton","Distrito Capital"),(44,"Lunea Scott","SH"),(45,"Amelia Pennington","SP"),(46,"Erin Beach","Suffolk"),(47,"Hilda Barber","Provence-Alpes-Côte d'Azur"),(48,"Francis Holloway","Junín"),(49,"Eric Knox","WA"),(50,"Galena Craft","ON");
INSERT INTO `farmer` (`id`,`name`,`village`) VALUES (51,"Quentin Terry","Gye"),(52,"Acton Calderon","SP"),(53,"Nevada May","Luxemburg"),(54,"Elmo Strickland","Bolívar"),(55,"Chase Floyd","Cumberland"),(56,"Minerva Raymond","Namen"),(57,"Summer Cruz","L"),(58,"Eric Kane","X"),(59,"Anastasia Bray","PUG"),(60,"Hadley Shelton","GO"),(61,"Ronan Waller","O"),(62,"Prescott Beck","NSW"),(63,"Callum Avila","Gilgit Baltistan"),(64,"Quinlan Garcia","ANT"),(65,"Omar Rowe","Piura"),(66,"Thaddeus Meyer","PK"),(67,"Naomi Marks","Namen"),(68,"Octavia Oliver","C"),(69,"Ali Malone","NI"),(70,"Briar Meyers","SMO"),(71,"Phelan Henry","Kentucky"),(72,"Remedios Witt","NSW"),(73,"Tarik Burks","Gaziantep"),(74,"Autumn Donovan","Zeeland"),(75,"Jenna Miranda","JB"),(76,"Preston Padilla","West Java"),(77,"Dane Rodriquez","Quebec"),(78,"Norman Schwartz","KP"),(79,"Reagan Simon","Pomorskie"),(80,"Brenda Bernard","Lampung"),(81,"Thaddeus Guerrero","Oyo"),(82,"Rinah Saunders","QLD"),(83,"Hyatt Manning","N."),(84,"Maisie Ryan","Antioquia"),(85,"Aubrey Wallace","Pernambuco"),(86,"Judith Floyd","MI"),(87,"Palmer Clements","AB"),(88,"Yoko Soto","SI"),(89,"Evan Cain","LU"),(90,"Kieran Dickson","Sląskie"),(91,"Lareina Clay","Central Java"),(92,"Alexa Cote","Burgenland"),(93,"Amir Alvarado","HR"),(94,"Xanthus Chaney","SJ"),(95,"Shelby Garcia","PIU"),(96,"Rigel Ray","Ov"),(97,"Farrah Coleman","Kirov Oblast"),(98,"Garth Yates","Noord Holland"),(99,"Louis Salinas","NO"),(100,"Mallory Bond","Gyeonggi");

INSERT INTO `users` (`active`,`credentials_expiration_date`,`expiration_date`,`locked`,`password`,`username`)
VALUES (1,'2020-01-01','2020-01-01',0,'$2a$10$8Zs9WYLX77m5T.EIthx4CupwaCJ1DNX0IRDdhPJmIgdT/XJZjvrum','adf');

INSERT INTO `roles` (`role_name`) VALUES ('ROLE_ADMIN');
INSERT INTO `roles` (`role_name`) VALUES ('ROLE_USER');

INSERT INTO `users_roles` VALUES (1,1);
INSERT INTO `users_roles` VALUES (1,2);